pool:
  vmImage: ubuntu-latest

stages:
- stage: SCA_
  jobs:
  - job: J2
    displayName: SCA
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
      - script: echo etapa SCA!
        displayName: 'Run dependency checks'
      - task: dependency-check-build-task@6
        inputs:
          projectName: 'spring-boot-kubernetes'
          scanPath: '$(Build.SourcesDirectory)/target/*'
          format: 'ALL'
          reportsDirectory: '$(Build.SourcesDirectory)/resultado'
      - script: |
          variable=$(grep ",HIGH," $(Build.SourcesDirectory)/dependency/dependency-check-report.csv | wc -l)
          echo $variable "HIGH Vulnerabilities detected with dependency-check"
          if [ $variable -gt 0 ];
          then 
            echo "Stop pipeline execution because dependency check detected" $variable " > 0 HIGH Vulnerabilities"
            exit 1;
          fi;

