pool:
  vmImage: ubuntu-latest


stages:
- stage: SAST_
  jobs:
  - job: J1
    displayName: SAST
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'Sonarcloud_serv_conx'
          organization: 'talfaro-bcn'
          projectKey: 'talfaro-bcn_spring-boot-kubernetes'
          projectName: 'spring-boot-kubernetes'
      
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: true
          sqMavenPluginVersionChoice: 'latest'
          
  - job: J2
    displayName: SCA
    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
    