pool:
  vmImage: ubuntu-latest

stages:
- stage: SCA_
  jobs:
  - job: J2
    displayName: SCA
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
      - script: echo etapa SCA!
        displayName: 'Run dependency checks'
      - task: dependency-check-build-task@6
        inputs:
          projectName: 'spring-boot-kubernetes'
          scanPath: '$(Build.SourcesDirectory)/target/*'
          format: 'ALL'
          reportsDirectory: '$(Build.SourcesDirectory)/resultado'

      
